// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8F1vo3meQCi0Yq0G61-g6HuseFGl1v4',
    appId: '1:903937770249:web:77b61d99366cb2789fc9d8',
    messagingSenderId: '903937770249',
    projectId: 'uridachi-3b4a3',
    authDomain: 'uridachi-3b4a3.firebaseapp.com',
    storageBucket: 'uridachi-3b4a3.appspot.com',
    measurementId: 'G-4GYBQJ33L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_QRhuDIwcR8zgPFOko6bRi8Kaat6H4s',
    appId: '1:903937770249:android:fd4c7f07feb0c79c9fc9d8',
    messagingSenderId: '903937770249',
    projectId: 'uridachi-3b4a3',
    storageBucket: 'uridachi-3b4a3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZuRRM0zV-JYQmckc09gakRHcWfa4EsU',
    appId: '1:903937770249:ios:6a68d8676c7d69a99fc9d8',
    messagingSenderId: '903937770249',
    projectId: 'uridachi-3b4a3',
    storageBucket: 'uridachi-3b4a3.appspot.com',
    iosBundleId: 'com.example.uridachi.RunnerTests',
  );
}
